"""add transactional search outbox schema

Revision ID: 02a14b4d18bf
Revises: 5d2c9a7e4b10
Create Date: 2026-07-17 14:35:43.345004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a14b4d18bf'
down_revision: Union[str, Sequence[str], None] = '5d2c9a7e4b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_index_outbox',
    sa.Column('outbox_id', sa.String(length=45), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=256), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=256), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("entity_type IN ('canonical_event', 'detection_signal', 'incident')", name='ck_search_index_outbox_entity_type'),
    sa.CheckConstraint("operation IN ('upsert')", name='ck_search_index_outbox_operation'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'retry', 'completed', 'failed')", name='ck_search_index_outbox_status'),
    sa.CheckConstraint('attempt_count >= 0 AND payload_size_bytes >= 0', name='ck_search_index_outbox_nonnegative'),
    sa.CheckConstraint('document_version > 0', name='ck_search_index_outbox_document_version'),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('deduplication_key', name='uq_search_index_outbox_deduplication')
    )
    op.create_index('ix_search_index_outbox_entity_lookup', 'search_index_outbox', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_search_index_outbox_lease_expires', 'search_index_outbox', ['lease_expires_at'], unique=False)
    op.create_index('ix_search_index_outbox_status_available', 'search_index_outbox', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_index_outbox_status_available', table_name='search_index_outbox')
    op.drop_index('ix_search_index_outbox_lease_expires', table_name='search_index_outbox')
    op.drop_index('ix_search_index_outbox_entity_lookup', table_name='search_index_outbox')
    op.drop_table('search_index_outbox')
    # ### end Alembic commands ###
