"""Add job association tables

Revision ID: 23d5176b8012
Revises: d2e1aa12897a
Create Date: 2026-07-13 11:23:07.426170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d5176b8012'
down_revision: Union[str, Sequence[str], None] = 'd2e1aa12897a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_job_events',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['canonical_events.event_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'event_id')
    )
    op.create_table('ingestion_job_incidents',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'incident_id')
    )
    op.create_table('ingestion_job_signals',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['detection_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'signal_id')
    )
    
    # Backfill data from existing columns
    op.execute("INSERT INTO ingestion_job_events (job_id, event_id) SELECT job_id, event_id FROM canonical_events WHERE job_id IS NOT NULL")
    op.execute("INSERT INTO ingestion_job_signals (job_id, signal_id) SELECT job_id, signal_id FROM detection_signals WHERE job_id IS NOT NULL")
    op.execute("INSERT INTO ingestion_job_incidents (job_id, incident_id) SELECT job_id, incident_id FROM incidents WHERE job_id IS NOT NULL")
    
    # Drop job_id columns using batch operations for SQLite compatibility
    with op.batch_alter_table('canonical_events', schema=None) as batch_op:
        batch_op.drop_index('ix_canonical_events_job_id')
        batch_op.drop_column('job_id')
        
    with op.batch_alter_table('detection_signals', schema=None) as batch_op:
        batch_op.drop_index('ix_detection_signals_job_id')
        batch_op.drop_column('job_id')
        
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_job_id')
        batch_op.drop_column('job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_incidents_job_id'), 'ingestion_jobs', ['job_id'], ['id'])
        
    with op.batch_alter_table('detection_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_detection_signals_job_id'), 'ingestion_jobs', ['job_id'], ['id'])
        
    with op.batch_alter_table('canonical_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_canonical_events_job_id', 'ingestion_jobs', ['job_id'], ['id'])

    # Reverse backfill (take the first job_id if multiple)
    op.execute("UPDATE canonical_events SET job_id = (SELECT job_id FROM ingestion_job_events WHERE event_id = canonical_events.event_id LIMIT 1)")
    op.execute("UPDATE detection_signals SET job_id = (SELECT job_id FROM ingestion_job_signals WHERE signal_id = detection_signals.signal_id LIMIT 1)")
    op.execute("UPDATE incidents SET job_id = (SELECT job_id FROM ingestion_job_incidents WHERE incident_id = incidents.incident_id LIMIT 1)")

    op.drop_table('ingestion_job_signals')
    op.drop_table('ingestion_job_incidents')
    op.drop_table('ingestion_job_events')
    # ### end Alembic commands ###
