"""Add job retry and lease fields

Revision ID: 554b54ed15b4
Revises: 63221e3b0cd4
Create Date: 2026-07-14 11:46:01.834130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554b54ed15b4'
down_revision: Union[str, Sequence[str], None] = '63221e3b0cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'last_attempt_at')
    op.drop_column('ingestion_jobs', 'lease_expires_at')
    op.drop_column('ingestion_jobs', 'next_retry_at')
    # ### end Alembic commands ###
