"""add background job fields

Revision ID: 63221e3b0cd4
Revises: 9688ccdecfd9
Create Date: 2026-07-13 21:10:19.250262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63221e3b0cd4'
down_revision: Union[str, Sequence[str], None] = '9688ccdecfd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('attempt_count', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('worker_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'worker_id')
    op.drop_column('ingestion_jobs', 'attempt_count')
    op.drop_column('ingestion_jobs', 'queued_at')
    # ### end Alembic commands ###
