"""Add metrics and report columns

Revision ID: 9688ccdecfd9
Revises: 23d5176b8012
Create Date: 2026-07-13 19:03:19.559977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9688ccdecfd9'
down_revision: Union[str, Sequence[str], None] = '23d5176b8012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('semantically_invalid_records', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('skipped_records', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('bytes_read', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'bytes_read')
    op.drop_column('ingestion_jobs', 'skipped_records')
    op.drop_column('ingestion_jobs', 'semantically_invalid_records')
    # ### end Alembic commands ###
