"""Initial schema

Revision ID: f34a07e35399
Revises: 
Create Date: 2026-07-12 16:08:51.301337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34a07e35399'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_signals',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.Column('target_entities', sa.JSON(), nullable=True),
    sa.Column('event_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_detection_signals_rule_id'), 'detection_signals', ['rule_id'], unique=False)
    op.create_table('incidents',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('incident_family', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_entity', sa.String(), nullable=True),
    sa.Column('target_entities', sa.JSON(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index(op.f('ix_incidents_primary_entity'), 'incidents', ['primary_entity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('input_format', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('parsed_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('unsupported_records', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('parser_counts', sa.JSON(), nullable=True),
    sa.Column('error_counts', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_source_name'), 'ingestion_jobs', ['source_name'], unique=False)
    op.create_table('log_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_sources_source_name'), 'log_sources', ['source_name'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_incident_id'), 'audit_events', ['incident_id'], unique=False)
    op.create_table('canonical_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('parser_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_message', sa.String(), nullable=True),
    sa.Column('original_log', sa.JSON(), nullable=True),
    sa.Column('normalized_fields', sa.JSON(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('dst_ip', sa.String(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_canonical_events_dst_ip'), 'canonical_events', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_canonical_events_job_id'), 'canonical_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_canonical_events_source_name'), 'canonical_events', ['source_name'], unique=False)
    op.create_index(op.f('ix_canonical_events_src_ip'), 'canonical_events', ['src_ip'], unique=False)
    op.create_index(op.f('ix_canonical_events_timestamp'), 'canonical_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_canonical_events_user'), 'canonical_events', ['user'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('is_context', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_event_id'), 'incident_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_table('incident_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('signal_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['detection_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_signals_incident_id'), 'incident_signals', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_signals_signal_id'), 'incident_signals', ['signal_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_incident_id'), 'reports', ['incident_id'], unique=False)
    op.create_table('triage_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('iteration_count', sa.Integer(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('search_history', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_runs_incident_id'), 'triage_runs', ['incident_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('triage_run_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('original_fields', sa.JSON(), nullable=True),
    sa.Column('correlation_context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['triage_run_id'], ['triage_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_triage_run_id'), 'evidence_items', ['triage_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_items_triage_run_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_triage_runs_incident_id'), table_name='triage_runs')
    op.drop_table('triage_runs')
    op.drop_index(op.f('ix_reports_incident_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_incident_signals_signal_id'), table_name='incident_signals')
    op.drop_index(op.f('ix_incident_signals_incident_id'), table_name='incident_signals')
    op.drop_table('incident_signals')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_event_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_canonical_events_user'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_timestamp'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_src_ip'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_source_name'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_job_id'), table_name='canonical_events')
    op.drop_index(op.f('ix_canonical_events_dst_ip'), table_name='canonical_events')
    op.drop_table('canonical_events')
    op.drop_index(op.f('ix_audit_events_incident_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_log_sources_source_name'), table_name='log_sources')
    op.drop_table('log_sources')
    op.drop_index(op.f('ix_ingestion_jobs_source_name'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_primary_entity'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_detection_signals_rule_id'), table_name='detection_signals')
    op.drop_table('detection_signals')
    # ### end Alembic commands ###
